[2021-05-16 22:41:56,402] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.loading_data_to_s3 2021-05-17T01:41:43.430521+00:00 [queued]>
[2021-05-16 22:41:56,408] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.loading_data_to_s3 2021-05-17T01:41:43.430521+00:00 [queued]>
[2021-05-16 22:41:56,408] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 22:41:56,408] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-16 22:41:56,408] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 22:41:56,416] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): loading_data_to_s3> on 2021-05-17T01:41:43.430521+00:00
[2021-05-16 22:41:56,419] {standard_task_runner.py:52} INFO - Started process 32870 to run task
[2021-05-16 22:41:56,426] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'loading_data_to_s3', '2021-05-17T01:41:43.430521+00:00', '--job-id', '844', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpt1y6364g', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpp748mm68']
[2021-05-16 22:41:56,427] {standard_task_runner.py:77} INFO - Job 844: Subtask loading_data_to_s3
[2021-05-16 22:41:56,457] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.loading_data_to_s3 2021-05-17T01:41:43.430521+00:00 [running]> on host 27.2.168.192.in-addr.arpa
[2021-05-16 22:41:56,482] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=loading_data_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2021-05-17T01:41:43.430521+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-17T01:41:43.430521+00:00
[2021-05-16 22:41:57,740] {logging_mixin.py:104} INFO - Fetching interval list
[2021-05-16 22:41:57,742] {logging_mixin.py:104} INFO - Inverval list built
[2021-05-16 22:41:57,743] {logging_mixin.py:104} INFO - Processing data
[2021-05-16 22:41:57,743] {logging_mixin.py:104} INFO - df initialized
[2021-05-16 22:41:57,745] {logging_mixin.py:104} INFO - (array([1621213413001, 1621213917000]), 1)
[2021-05-16 22:41:57,746] {logging_mixin.py:104} INFO - (array([1621213413001, 1621213917000]), 2)
[2021-05-16 22:41:57,747] {logging_mixin.py:104} INFO - (array([1621213413001, 1621213917000]), 3)
[2021-05-16 22:41:57,747] {logging_mixin.py:104} INFO - ThreadPoolExecutor initialized
[2021-05-16 22:41:57,748] {logging_mixin.py:104} INFO - running function for: (array([1621213413001, 1621213917000]), 1)
[2021-05-16 22:41:57,749] {logging_mixin.py:104} INFO - https://cdn.iqoption.com/api/quotes-history/quotes/3.0?to=1621213917000&from=1621213413001&active_id=1&only_round=true&_key=1614903660000
[2021-05-16 22:41:57,750] {logging_mixin.py:104} INFO - submitted
[2021-05-16 22:41:57,751] {logging_mixin.py:104} INFO - running function for: (array([1621213413001, 1621213917000]), 2)
[2021-05-16 22:41:57,752] {logging_mixin.py:104} INFO - https://cdn.iqoption.com/api/quotes-history/quotes/3.0?to=1621213917000&from=1621213413001&active_id=2&only_round=true&_key=1614903660000
[2021-05-16 22:41:57,752] {logging_mixin.py:104} INFO - submitted
[2021-05-16 22:41:57,753] {logging_mixin.py:104} INFO - running function for: (array([1621213413001, 1621213917000]), 3)
[2021-05-16 22:41:57,753] {logging_mixin.py:104} INFO - https://cdn.iqoption.com/api/quotes-history/quotes/3.0?to=1621213917000&from=1621213413001&active_id=3&only_round=true&_key=1614903660000
[2021-05-16 22:41:57,754] {logging_mixin.py:104} INFO - submitted
[2021-05-16 22:42:00,416] {python.py:118} INFO - Done. Returned value was: None
[2021-05-16 22:42:00,422] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=loading_data_to_s3, execution_date=20210517T014143, start_date=20210517T014156, end_date=20210517T014200
[2021-05-16 22:42:00,466] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-16 22:42:00,475] {local_task_job.py:146} INFO - Task exited with return code 0
