[2021-05-14 18:13:48,972] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.loading_data_to_s3 2021-05-14T21:13:35.371564+00:00 [queued]>
[2021-05-14 18:13:48,978] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.loading_data_to_s3 2021-05-14T21:13:35.371564+00:00 [queued]>
[2021-05-14 18:13:48,979] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 18:13:48,979] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-14 18:13:48,979] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 18:13:48,984] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): loading_data_to_s3> on 2021-05-14T21:13:35.371564+00:00
[2021-05-14 18:13:48,988] {standard_task_runner.py:52} INFO - Started process 24769 to run task
[2021-05-14 18:13:48,994] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'loading_data_to_s3', '2021-05-14T21:13:35.371564+00:00', '--job-id', '526', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmppxoep9_8', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpwcmiat3n']
[2021-05-14 18:13:48,996] {standard_task_runner.py:77} INFO - Job 526: Subtask loading_data_to_s3
[2021-05-14 18:13:49,028] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.loading_data_to_s3 2021-05-14T21:13:35.371564+00:00 [running]> on host 27.2.168.192.in-addr.arpa
[2021-05-14 18:13:49,051] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=loading_data_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2021-05-14T21:13:35.371564+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-14T21:13:35.371564+00:00
[2021-05-14 18:13:50,462] {logging_mixin.py:104} INFO - Fetching interval list
[2021-05-14 18:13:50,464] {logging_mixin.py:104} INFO - Inverval list built
[2021-05-14 18:13:50,464] {logging_mixin.py:104} INFO - Processing data
[2021-05-14 18:13:50,465] {logging_mixin.py:104} INFO - df initialized
[2021-05-14 18:13:50,466] {logging_mixin.py:104} INFO - ThreadPoolExecutor initialized
[2021-05-14 18:13:50,467] {logging_mixin.py:104} INFO - running function for: (array([1621023230000, 1621025030000]), 1)
[2021-05-14 18:13:50,468] {logging_mixin.py:104} INFO - https://cdn.iqoption.com/api/quotes-history/quotes/3.0?to=1621025030000&from=1621023230000&active_id=1&only_round=true&_key=1614903660000
[2021-05-14 18:13:50,468] {logging_mixin.py:104} INFO - https://cdn.iqoption.com/api/quotes-history/quotes/3.0?to=1621025030000&from=1621023230000&active_id=1&only_round=true&_key=1614903660000
submitted
[2021-05-14 18:13:50,470] {logging_mixin.py:104} INFO - running function for: (array([1621023230000, 1621025030000]), 2)
[2021-05-14 18:13:50,470] {logging_mixin.py:104} INFO - https://cdn.iqoption.com/api/quotes-history/quotes/3.0?to=1621025030000&from=1621023230000&active_id=2&only_round=true&_key=1614903660000
[2021-05-14 18:13:50,471] {logging_mixin.py:104} INFO - submitted
[2021-05-14 18:13:50,472] {logging_mixin.py:104} INFO - running function for: (array([1621023230000, 1621025030000]), 3)
[2021-05-14 18:13:50,472] {logging_mixin.py:104} INFO - https://cdn.iqoption.com/api/quotes-history/quotes/3.0?to=1621025030000&from=1621023230000&active_id=3&only_round=true&_key=1614903660000
[2021-05-14 18:13:50,473] {logging_mixin.py:104} INFO - https://cdn.iqoption.com/api/quotes-history/quotes/3.0?to=1621025030000&from=1621023230000&active_id=3&only_round=true&_key=1614903660000
submitted
[2021-05-14 18:13:55,286] {python.py:118} INFO - Done. Returned value was: None
[2021-05-14 18:13:55,292] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=loading_data_to_s3, execution_date=20210514T211335, start_date=20210514T211348, end_date=20210514T211355
[2021-05-14 18:13:55,336] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-14 18:13:55,376] {local_task_job.py:146} INFO - Task exited with return code 0
