[2021-05-14 09:50:57,077] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_main_table 2021-05-14T00:00:00+00:00 [queued]>
[2021-05-14 09:50:57,083] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_main_table 2021-05-14T00:00:00+00:00 [queued]>
[2021-05-14 09:50:57,083] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 09:50:57,083] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-14 09:50:57,083] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 09:50:57,092] {taskinstance.py:1089} INFO - Executing <Task(ExecuteQueryOperator): create_main_table> on 2021-05-14T00:00:00+00:00
[2021-05-14 09:50:57,096] {standard_task_runner.py:52} INFO - Started process 18354 to run task
[2021-05-14 09:50:57,104] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'create_main_table', '2021-05-14T00:00:00+00:00', '--job-id', '337', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpbc6umnpb', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmp2fsmhxxe']
[2021-05-14 09:50:57,106] {standard_task_runner.py:77} INFO - Job 337: Subtask create_main_table
[2021-05-14 09:50:57,144] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.create_main_table 2021-05-14T00:00:00+00:00 [running]> on host 27.2.168.192.in-addr.arpa
[2021-05-14 09:50:57,173] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=create_main_table
AIRFLOW_CTX_EXECUTION_DATE=2021-05-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-14T00:00:00+00:00
[2021-05-14 09:50:57,175] {execute_query.py:21} INFO - Executing query
[2021-05-14 09:50:57,178] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.caua6g9a7jto.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-05-14 09:50:58,271] {dbapi.py:180} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS forex.binary_options_historical_quotes (
        quote_sk BIGINT IDENTITY (0, 1),
        date_seconds TIMESTAMP,
        active_id INT,
        value NUMERIC (10, 6),
        PRIMARY KEY (quote_sk)
    );
, parameters: None
[2021-05-14 09:50:58,581] {dbapi.py:186} INFO - Rows affected: -1
[2021-05-14 09:50:58,784] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_main_table, execution_date=20210514T000000, start_date=20210514T125057, end_date=20210514T125058
[2021-05-14 09:50:58,840] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-14 09:50:58,859] {local_task_job.py:146} INFO - Task exited with return code 0
