[2021-05-14 19:27:02,576] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.remove_s3_files 2021-05-14T22:24:29.228682+00:00 [queued]>
[2021-05-14 19:27:02,584] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.remove_s3_files 2021-05-14T22:24:29.228682+00:00 [queued]>
[2021-05-14 19:27:02,584] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 19:27:02,584] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-14 19:27:02,584] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 19:27:02,592] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): remove_s3_files> on 2021-05-14T22:24:29.228682+00:00
[2021-05-14 19:27:02,595] {standard_task_runner.py:52} INFO - Started process 25700 to run task
[2021-05-14 19:27:02,601] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'remove_s3_files', '2021-05-14T22:24:29.228682+00:00', '--job-id', '568', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpa7970ugh', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpgfw9d8uh']
[2021-05-14 19:27:02,603] {standard_task_runner.py:77} INFO - Job 568: Subtask remove_s3_files
[2021-05-14 19:27:02,636] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.remove_s3_files 2021-05-14T22:24:29.228682+00:00 [running]> on host 27.2.168.192.in-addr.arpa
[2021-05-14 19:27:02,658] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=remove_s3_files
AIRFLOW_CTX_EXECUTION_DATE=2021-05-14T22:24:29.228682+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-14T22:24:29.228682+00:00
[2021-05-14 19:27:05,616] {python.py:118} INFO - Done. Returned value was: None
[2021-05-14 19:27:05,620] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=remove_s3_files, execution_date=20210514T222429, start_date=20210514T222702, end_date=20210514T222705
[2021-05-14 19:27:05,668] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-14 19:27:05,711] {local_task_job.py:146} INFO - Task exited with return code 0
